var hierarchy =
[
    [ "AlgoritmoDelPintor", "class_algoritmo_del_pintor.html", null ],
    [ "EspacioDeTrabajo", "class_espacio_de_trabajo.html", null ],
    [ "std::exception", null, [
      [ "std::runtime_error", null, [
        [ "ExcepcionArchivoCorrupto", "class_excepcion_archivo_corrupto.html", null ],
        [ "ExcepcionArchivoNoSoportado", "class_excepcion_archivo_no_soportado.html", null ]
      ] ]
    ] ],
    [ "Filtros", "class_filtros.html", [
      [ "Binarizado", "class_binarizado.html", null ],
      [ "Brillo", "class_brillo.html", null ],
      [ "Contraste", "class_contraste.html", null ],
      [ "FiltroMediana", "class_filtro_mediana.html", null ],
      [ "FiltroPasaAltos", "class_filtro_pasa_altos.html", null ],
      [ "FiltroPasaBajos", "class_filtro_pasa_bajos.html", null ],
      [ "Negativo", "class_negativo.html", null ]
    ] ],
    [ "GestorDeArchivos", "class_gestor_de_archivos.html", [
      [ "ArchivosAIC", "class_archivos_a_i_c.html", null ],
      [ "ArchivosPNM", "class_archivos_p_n_m.html", null ]
    ] ],
    [ "Imagen", "class_imagen.html", null ],
    [ "Pixel", "class_pixel.html", null ],
    [ "Posicion", "struct_posicion.html", null ],
    [ "ProcesadorEstadistico", "class_procesador_estadistico.html", null ],
    [ "QObject", "class_q_object.html", [
      [ "EI_AutoTest", "class_e_i___auto_test.html", null ]
    ] ],
    [ "QOpenGLFunctions", "class_q_open_g_l_functions.html", [
      [ "GraficadorHistograma", "class_graficador_histograma.html", null ],
      [ "VentanaDeGraficacion", "class_ventana_de_graficacion.html", null ]
    ] ],
    [ "QOpenGLWidget", "class_q_open_g_l_widget.html", [
      [ "GraficadorHistograma", "class_graficador_histograma.html", null ],
      [ "VentanaDeGraficacion", "class_ventana_de_graficacion.html", null ]
    ] ],
    [ "qt_meta_stringdata_QCP_t", "structqt__meta__stringdata___q_c_p__t.html", null ],
    [ "qt_meta_stringdata_QCPAbstractItem_t", "structqt__meta__stringdata___q_c_p_abstract_item__t.html", null ],
    [ "qt_meta_stringdata_QCPAbstractLegendItem_t", "structqt__meta__stringdata___q_c_p_abstract_legend_item__t.html", null ],
    [ "qt_meta_stringdata_QCPAbstractPlottable_t", "structqt__meta__stringdata___q_c_p_abstract_plottable__t.html", null ],
    [ "qt_meta_stringdata_QCPAxis_t", "structqt__meta__stringdata___q_c_p_axis__t.html", null ],
    [ "qt_meta_stringdata_QCPAxisRect_t", "structqt__meta__stringdata___q_c_p_axis_rect__t.html", null ],
    [ "qt_meta_stringdata_QCPAxisTicker_t", "structqt__meta__stringdata___q_c_p_axis_ticker__t.html", null ],
    [ "qt_meta_stringdata_QCPAxisTickerFixed_t", "structqt__meta__stringdata___q_c_p_axis_ticker_fixed__t.html", null ],
    [ "qt_meta_stringdata_QCPAxisTickerPi_t", "structqt__meta__stringdata___q_c_p_axis_ticker_pi__t.html", null ],
    [ "qt_meta_stringdata_QCPAxisTickerTime_t", "structqt__meta__stringdata___q_c_p_axis_ticker_time__t.html", null ],
    [ "qt_meta_stringdata_QCPBars_t", "structqt__meta__stringdata___q_c_p_bars__t.html", null ],
    [ "qt_meta_stringdata_QCPBarsGroup_t", "structqt__meta__stringdata___q_c_p_bars_group__t.html", null ],
    [ "qt_meta_stringdata_QCPColorGradient_t", "structqt__meta__stringdata___q_c_p_color_gradient__t.html", null ],
    [ "qt_meta_stringdata_QCPColorMap_t", "structqt__meta__stringdata___q_c_p_color_map__t.html", null ],
    [ "qt_meta_stringdata_QCPColorScale_t", "structqt__meta__stringdata___q_c_p_color_scale__t.html", null ],
    [ "qt_meta_stringdata_QCPColorScaleAxisRectPrivate_t", "structqt__meta__stringdata___q_c_p_color_scale_axis_rect_private__t.html", null ],
    [ "qt_meta_stringdata_QCPCurve_t", "structqt__meta__stringdata___q_c_p_curve__t.html", null ],
    [ "qt_meta_stringdata_QCPErrorBars_t", "structqt__meta__stringdata___q_c_p_error_bars__t.html", null ],
    [ "qt_meta_stringdata_QCPFinancial_t", "structqt__meta__stringdata___q_c_p_financial__t.html", null ],
    [ "qt_meta_stringdata_QCPGraph_t", "structqt__meta__stringdata___q_c_p_graph__t.html", null ],
    [ "qt_meta_stringdata_QCPGrid_t", "structqt__meta__stringdata___q_c_p_grid__t.html", null ],
    [ "qt_meta_stringdata_QCPItemAnchor_t", "structqt__meta__stringdata___q_c_p_item_anchor__t.html", null ],
    [ "qt_meta_stringdata_QCPItemBracket_t", "structqt__meta__stringdata___q_c_p_item_bracket__t.html", null ],
    [ "qt_meta_stringdata_QCPItemCurve_t", "structqt__meta__stringdata___q_c_p_item_curve__t.html", null ],
    [ "qt_meta_stringdata_QCPItemEllipse_t", "structqt__meta__stringdata___q_c_p_item_ellipse__t.html", null ],
    [ "qt_meta_stringdata_QCPItemLine_t", "structqt__meta__stringdata___q_c_p_item_line__t.html", null ],
    [ "qt_meta_stringdata_QCPItemPixmap_t", "structqt__meta__stringdata___q_c_p_item_pixmap__t.html", null ],
    [ "qt_meta_stringdata_QCPItemPosition_t", "structqt__meta__stringdata___q_c_p_item_position__t.html", null ],
    [ "qt_meta_stringdata_QCPItemRect_t", "structqt__meta__stringdata___q_c_p_item_rect__t.html", null ],
    [ "qt_meta_stringdata_QCPItemStraightLine_t", "structqt__meta__stringdata___q_c_p_item_straight_line__t.html", null ],
    [ "qt_meta_stringdata_QCPItemText_t", "structqt__meta__stringdata___q_c_p_item_text__t.html", null ],
    [ "qt_meta_stringdata_QCPItemTracer_t", "structqt__meta__stringdata___q_c_p_item_tracer__t.html", null ],
    [ "qt_meta_stringdata_QCPLabelPainterPrivate_t", "structqt__meta__stringdata___q_c_p_label_painter_private__t.html", null ],
    [ "qt_meta_stringdata_QCPLayer_t", "structqt__meta__stringdata___q_c_p_layer__t.html", null ],
    [ "qt_meta_stringdata_QCPLayerable_t", "structqt__meta__stringdata___q_c_p_layerable__t.html", null ],
    [ "qt_meta_stringdata_QCPLayout_t", "structqt__meta__stringdata___q_c_p_layout__t.html", null ],
    [ "qt_meta_stringdata_QCPLayoutElement_t", "structqt__meta__stringdata___q_c_p_layout_element__t.html", null ],
    [ "qt_meta_stringdata_QCPLayoutGrid_t", "structqt__meta__stringdata___q_c_p_layout_grid__t.html", null ],
    [ "qt_meta_stringdata_QCPLayoutInset_t", "structqt__meta__stringdata___q_c_p_layout_inset__t.html", null ],
    [ "qt_meta_stringdata_QCPLegend_t", "structqt__meta__stringdata___q_c_p_legend__t.html", null ],
    [ "qt_meta_stringdata_QCPLineEnding_t", "structqt__meta__stringdata___q_c_p_line_ending__t.html", null ],
    [ "qt_meta_stringdata_QCPMarginGroup_t", "structqt__meta__stringdata___q_c_p_margin_group__t.html", null ],
    [ "qt_meta_stringdata_QCPPainter_t", "structqt__meta__stringdata___q_c_p_painter__t.html", null ],
    [ "qt_meta_stringdata_QCPPlottableLegendItem_t", "structqt__meta__stringdata___q_c_p_plottable_legend_item__t.html", null ],
    [ "qt_meta_stringdata_QCPPolarAxisAngular_t", "structqt__meta__stringdata___q_c_p_polar_axis_angular__t.html", null ],
    [ "qt_meta_stringdata_QCPPolarAxisRadial_t", "structqt__meta__stringdata___q_c_p_polar_axis_radial__t.html", null ],
    [ "qt_meta_stringdata_QCPPolarGraph_t", "structqt__meta__stringdata___q_c_p_polar_graph__t.html", null ],
    [ "qt_meta_stringdata_QCPPolarGrid_t", "structqt__meta__stringdata___q_c_p_polar_grid__t.html", null ],
    [ "qt_meta_stringdata_QCPPolarLegendItem_t", "structqt__meta__stringdata___q_c_p_polar_legend_item__t.html", null ],
    [ "qt_meta_stringdata_QCPScatterStyle_t", "structqt__meta__stringdata___q_c_p_scatter_style__t.html", null ],
    [ "qt_meta_stringdata_QCPSelectionDecorator_t", "structqt__meta__stringdata___q_c_p_selection_decorator__t.html", null ],
    [ "qt_meta_stringdata_QCPSelectionDecoratorBracket_t", "structqt__meta__stringdata___q_c_p_selection_decorator_bracket__t.html", null ],
    [ "qt_meta_stringdata_QCPSelectionRect_t", "structqt__meta__stringdata___q_c_p_selection_rect__t.html", null ],
    [ "qt_meta_stringdata_QCPStatisticalBox_t", "structqt__meta__stringdata___q_c_p_statistical_box__t.html", null ],
    [ "qt_meta_stringdata_QCPTextElement_t", "structqt__meta__stringdata___q_c_p_text_element__t.html", null ],
    [ "qt_meta_stringdata_QCustomPlot_t", "structqt__meta__stringdata___q_custom_plot__t.html", null ],
    [ "Sistema", "class_sistema.html", null ],
    [ "TablaLut", "class_tabla_lut.html", null ]
];